baseURL = "http://ecclespark.info/"
languageCode = "en-us"
title = "Eccles Park Ward Information"

disableKinds = ["taxonomy", "term"]
ignoreErrors = ["error-disable-taxonomy"]

[module]
[[module.mounts]]
source = "assets"
target = "assets"
[[module.mounts]]
source = "static"
target = "static"
[[module.imports]]
path = "github.com/sindresorhus/modern-normalize"
[[module.imports.mounts]]
source = "modern-normalize.css"
target = "static/scss/_modern-normalize.scss"
[[module.mounts]]
source = "node_modules/modern-normalize/modern-normalize.css"
target = "static/css/modern-normalize.css"
[[module.mounts]]
source = "node_modules/modern-normalize/modern-normalize.css"
target = "assets/scss/_modern-normalize.css"
